CREATE TABLE preguntas(
	id INT PRIMARY KEY AUTO_INCREMENT,
    pregunta text,
    respuesta text
    );

INSERT into preguntas (pregunta,respuesta)
values('hola','Hola! Nosotros somos GALyLEO ¿En qué podemos ayudarte?'),
('alvarez alvalos carretero yudhack','alvarez alvalos carretero corradini yudhack'),
('Soñaban con ser astronauta desde chicos?','Claro! Nos dimos cuenta de que queríamos ser astronautas cuando éramos muy jóvenes. ¡Nos estaban programando y lo supimos! '),
('Es difícil convertirse en astronauta?','Para nada! Sólo tenés que venir al Planetario de Buenos Aires y sentir lo que es ser un verdadero astronauta. '),
('Qué se siente estar en el espacio?','Estar en el espacio es algo que todos deberían vivir, te cambia la forma de pensar. '),
('Qué necesita un joven para convertirse en astronauta?','Estudiar, entrenamiento físico, visitar el Planetario de Buenos Aires, entre otras cosas. '),
('Pueden volar los pájaros en el espacio?','No. '),
('Tiene final el espacio?','Asumimos que no, pero en realidad nadie lo sabe. '),
('¿Cómo se creó el espacio?','Según la teoría actual, en una gran explosión llamada Big Bang. '),
('Cuánto pesa un transbordador espacial?','2.041 toneladas métricas (2.041.065 kilos) en el despegue. '),
('¿Se pueden ver las estrellas desde el espacio?','Sí.'),
('A qué velocidad se mueve la estación espacial Internacional?','28.163 km/h.'),
('temperatura en el espacio exterior','-270 grados Celsius, pero no significa mucho porque es en vacío. '),
('Qué es la zona Ricitos de Oro?','Ricitos de Oro es la zona de habitabilidad alrededor de una estrella en la que la temperatura no es ni muy caliente ni muy fría. Se llama así en honor al cuento. '),
('Qué hay en la órbita terrestre?','La Luna, la Estación Espacial Internacional y alrededor de 1.700 satélites '),
('Cuánto tiempo se tarda en dar una vuelta completa a la Tierra?','Depende de la altura, la Luna da una vuelta completa cada 27 días, la ISS cada 90 minutos. '),
('¿Por qué Marte se llama así','En honor del dios griego de la guerra, Marte, probablemente por su tonalidad rojiza. Los romanos nombraron los cinco planetas más brillantes con los nombres de sus dioses. '),
('Qué es un cosmonauta?','Un astronauta ruso. '),
('Se envejece en el espacio?','Sí, pero un poco más lento que en la Tierra. '),
('Qué es una sonda espacial','Un vehículo no tripulado que recorre el espacio recopilando datos y envía esos datos de vuelta a la Tierra para su estudio. '),
('Marte tiene gravedad','Sí, pero solo un 38% de la terrestre. '),
('A qué velocidad máxima puede ir un transbordador espacial?','28.163 km/h (la misma que la ISS)'),
('Qué es el espacio-tiempo?','Una medida teórica que interpreta las tras dimensiones que vemos en el espacio más una cuarta flecha que representa el tiempo.'),
('Podemos vivir en Marte?', 'No tal cual. Hace falta un soporte vital adecuado para resistir sus condiciones hostiles. '),
('A qué distancia está el espacio?','Si lo medimos desde la superficie terrestre a nivel del mar comienza a unos 100 km de altura. '),
('Por qué el espacio es negro?','Porque nuestra vista no es lo bastante aguda como para ver la luz de fondo. '),
('Quién fue la primera mujer en el espacio?','Valentina Tereshkova. '),
('Dónde está el cinturón de asteroides?','Entre las órbitas de Marte y Júpiter. '),
('Cuándo se descubrió Marte?','No se sabe, los astrónomos babilonios ya lo conocían en el año 400 antes de Cristo. '),
('Qué es una órbita?', 'La trayectoria circular de un objeto al moverse alrededor de un planeta o estrella. '),
('Se puede ver la Gran Muralla China desde el espacio a simple vista?','No, es un mito. '),
('Se puede ver Marte desde la Tierra?','Sí, pero solo de noche. Su brillo depende de la fecha. '),
('Marte tiene atmósfera?','Sí, pero no es respirable para el ser humano. '),
('Quién fue el primer ser humano en llegar al espacio','Yuri Gagarin. '),
('Cuánto se tarda en llegar al espacio?','Depende de la nave. Unos 9 minutos a bordo de un transbordador. Los Falcon 9 de SpaceX tardan 10. '),
('Dónde está la Estación Espacial Internacional?','Constantemente en movimiento sobre la órbita terrestre. '),
('Cuánto dura un año marciano?','687 días terrestres. '),
('Es Marte más grande que la Tierra?','No. '),
('Por qué Marte es rojo?','Por el óxido de hierro que cubre su superficie. '),
('Es el espacio un vacío?','El vacío perfecto no existe, pero el espacio se le acerca mucho. '),
('Cuál es la temperatura en Marte?','Máxima: 30º Celsius, Mínima: -175º Celsius. Media: -62º Celsius. '),
('Se pueden oír sonidos en el espacio?','El sonido existe en el espacio, pero los seres humanos no pueden oirlo. '),
('Qué es un asteroide','Es un cuerpo rocoso demasiado pequeño para ser un planeta. '),
('Hay vida en Marte?','No que nosotros sepamos. '),
('Cuántas lunas tiene Marte?','Dos, Deimos y Fobos.'),
('Qué significa NASA?','National Aeronautics and Space Administration. '),
('Cuánto se tarda en llegar a Marte?','Entre seis y nueve meses. El Curiosity Rover tardó 254 días (8,3 meses). ');
